name: MSYS2 PKGBUILD CI

on: [push, pull_request]

jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "!./.github/**"
          if-these-paths-change-return-all-included-paths: "./.github/**"
  build-pkg:
    runs-on: windows-latest
    needs: [detect-directory-changes]
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    steps:
    - uses: actions/checkout@v5
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANGARM64
        update: true
        install: >
            git make patch patchutils
        pacboy:
            toolchain:a
            gcc-compat:a
            cmake:a
            diffutils:a

    - name: run makepkg-mingw ${{ matrix.project }}
      working-directory: ./${{ matrix.project }}
      with:
        msystem: CLANGARM64
      shell: msys2 {0}
      run: |
        # makepkg-mingw on project directory: ${{ matrix.project }}
        makepkg-mingw --cleanbuild --force --noconfirm --syncdeps --skippgpcheck