name: MSYS2 PKGBUILD CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.vscode/**'
      - '.devcontainer/**'
  pull_request:

jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "!./.github/**"
  build-pkg:
    runs-on: windows-11-arm
    needs: [detect-directory-changes]
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    steps:
    - uses: actions/checkout@v5
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANGARM64
        update: true
        install:
            git
            make
            patch
            patchutils
        pacboy:
            toolchain:a
            gcc-compat:a
            cmake:a
            diffutils:a
    - name: makepkg-mingw
      working-directory: ./${{ matrix.project }}
      shell: msys2 {0}
      run: |
        # makepkg-mingw on project directory: ${{ matrix.project }}
        makepkg-mingw --cleanbuild --force --noconfirm --syncdeps --skippgpcheck
    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.project }}-aarch64
        path: ./${{ matrix.project }}/*.zst
  make-release:
    runs-on: ubuntu-latest
    needs: [build-pkg]
    steps:
      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
